// Generated by LiveScript 1.5.0
var webpack, minify;
webpack = require('webpack');
minify = -1 !== process.argv.indexOf('--minify');
module.exports = {
  entry: ['./index.ls'],
  output: {
    path: './dist',
    filename: minify ? 'hello.min.js' : 'hello.js'
  },
  module: {
    loaders: [{
      test: /\.ls$/,
      exclude: /node_modules/,
      loader: 'livescript-loader'
    }]
  },
  resolve: {
    extensions: ['', '.js', '.ls']
  },
  plugins: minify
    ? [new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })]
    : []
};
if (minify) {
  import$(module.exports.output, {
    libraryTarget: 'var',
    library: 'Boilerplate'
  });
}
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
